"""db minor upgrade

Revision ID: bd77af312094
Revises: d7ac98d65f76
Create Date: 2023-04-17 20:04:22.884702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd77af312094'
down_revision = 'd7ac98d65f76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('product_user_ds_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['user_id'])
    op.drop_column('product', 'user_ds')
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('product', sa.Column('user_ds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_user_ds_fkey', 'product', 'user', ['user_ds'], ['user_id'])
    op.drop_column('product', 'user_id')
    # ### end Alembic commands ###
