"""db creation

Revision ID: d7ac98d65f76
Revises: 
Create Date: 2023-04-17 19:04:39.074771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ac98d65f76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('track', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('product',
    sa.Column('article', sa.Integer(), nullable=False),
    sa.Column('user_ds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_ds'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_ds')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('user')
    # ### end Alembic commands ###
