version: "3.8"
services:
  psql_server:
    image: postgres:alpine3.17
    container_name: psql_server
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wildberries
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wildberries"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wb_net
  geckodrive:
    image: instrumentisto/geckodriver
    container_name: gecko_container
    ports:
      - "4444:4444"
    depends_on:
      - psql_server
    command: --binary=/opt/firefox/firefox --log=debug --host=0.0.0.0
    networks:
      - wb_net
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    env_file:
      - .env
    environment:
      HOST: psql_server
    volumes:
      - ./bot:/app
    depends_on:
      - psql_server
    networks:
      - wb_net
  parser:
    build:
      context: .
      dockerfile: script/Dockerfile
    container_name: parser
    env_file:
      - .env
    environment:
      HOST: psql_server
      COMMAND_EXECUTOR: "172.18.0.1"
    volumes:
      - ./script:/app
    depends_on:
      - psql_server
      - geckodrive
    networks:
      - wb_net
networks:
  wb_net:
    external: true
    name: wb_net