version: "3.8"
services:
  psql_server:
    image: postgres:alpine3.17
    container_name: psql_server
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=wildberries
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wildberries"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: "1G"
    networks:
      - your_net
  geckodrive:
    image: instrumentisto/geckodriver
    container_name: gecko
    ports:
      - "4444:4444"
    deploy:
      resources:
        limits:
          memory: "1G"
    command: --binary=/opt/firefox/firefox --log=debug host=0.0.0.0
    networks:
      - your_net
  bot:
    build: .
    container_name: bot
    environment:
      - TOKEN=YOUR_TOKEN
      - ADMIN_ID=YOUR_ID
      - ADMIN_USERNAME=YOUR_USERNAME
      - DRIVERNAME=postgresql
      - USERNAMEDB=postgres
      - PASSWORD=postgres
      - HOST=172.18.0.1
      - PORT=5433
      - COMMAND_EXECUTOR=172.18.0.1
      - DATABASE=wildberries
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    networks:
      - your_net
  parser:
    image: parser:final
    container_name: parser
    environment:
      - TOKEN=YOUR_TOKEN
      - ADMIN_ID=YOUR_ID
      - ADMIN_USERNAME=YOUR_USERNAME
      - DRIVERNAME=postgresql
      - USERNAMEDB=postgres
      - PASSWORD=postgres
      - HOST=172.18.0.1
      - PORT=5433
      - COMMAND_EXECUTOR=172.18.0.1
      - DATABASE=wildberries
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    networks:
      - your_net
networks:
  your_net:
    external: true
    name: your_net